//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Persistence.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE FUNCTION {0}() 
        ///RETURNS TRIGGER AS $$
        ///BEGIN
        ///    NEW.{1} = now();
        ///    RETURN NEW; 
        ///END;
        ///$$ language &apos;plpgsql&apos;;.
        /// </summary>
        internal static string func_dtt_create {
            get {
                return ResourceManager.GetString("func_dtt_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE public.{0}(uuid uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),{1});
        ///ALTER TABLE public.{0} OWNER to postgres;
        ///.
        /// </summary>
        internal static string tbl_create {
            get {
                return ResourceManager.GetString("tbl_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER {0}
        ///{1} {2}
        ///ON public.{3}
        ///FOR EACH ROW
        ///EXECUTE PROCEDURE public.{4}();
        ///
        ///.
        /// </summary>
        internal static string trg_dtt_create {
            get {
                return ResourceManager.GetString("trg_dtt_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW public.{0}({1})
        ///AS
        ///{2}
        ///ALTER TABLE public.{0} OWNER TO postgres;.
        /// </summary>
        internal static string view_create {
            get {
                return ResourceManager.GetString("view_create", resourceCulture);
            }
        }
    }
}
